### ISSUE TITLE
Analysis of Events

### ISSUE THREAD

**Issue by eridal** [cloudant-labs/cloudant-follow#141]
## Bug Description

Hi all,

This is not a bug report but I've made an analysis of the follow's library and wanted to share with you all as, I believe, there are quite surprising findings.

I'm trying to figure why the `timeout` event happens, and I still haven't found an answer even after this analysis; so any piece of advice will be greatly appreciated.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

The gist could be found here: https://gist.github.com/eridal/1390580c3d729faf1575dec6cafe50e2

And here are the events workflow, where edges mean..

- **solid**: a common or happy path, which will most certainly be used
- **dashed**: an alternative or optional path, which depends on certain condition to be followed
- **dotted**: an error path, which requires something going wrong to be followed

![events analysis](https://gist.githubusercontent.com/eridal/1390580c3d729faf1575dec6cafe50e2/raw/67146437b10586895ae06e4be9bcfbb40c92a33d/events.jpg)

### 2. What you expected to happen

Nothing really. I was doing this analysis to understand when and why events occur.

### 3. What actually happened

I found a few surprising facts:

1. **there are undocumented events**
- `query(req)`: emitted when a request to the server is made
- `response(resp)`: emitted when such response was correctly parsed

2. **the start/stop event can happen multiple times**

This might not be surprising for someone with a deep understanding of how the library work, and it is not clear on the event description that these events could happen multiple times.

> Idea: the library could include two more events, let say `init` and `finish` that fire only once and which could help clients react to the library's life-cycle.

3. **there are timeouts that wont fire the timeout event**

There are quite a few examples of this, for instance the `query` method will emit `retry` when the timeout handler executes.

Another example happens at `change`, when the `on_inactivity` handler will emit a `restart`

## Environment details

- Version(s) that are affected by this issue.
    > 8.2.2
- Node.js version
    > 10.15.3

**Comment by ricellis** [comment]
Because `request` has been deprecated, this library will also be deprecated. Nano will use a new changes reader for it's follow requests, see https://github.com/apache/couchdb-nano/pull/208

**Comment by eridal** [comment]
@ricellis thanks for the update!

Any idea when this will land on master?

**Comment by ricellis** [comment]
Sorry, I don't know, but I believe it will be the Nano 9.x release.
