### ISSUE TITLE
'request' package needs to be replaced

### ISSUE THREAD

**Issue by anushreemjoshi** [cloudant-labs/cloudant-follow#144]
## Bug Description
Replace 'request' package since it is deprecated.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue
Security issue is reported for http-signature package that is used in 'request' package which is already deprecated.
Request to please replace 'request' package since it is deprecated.

### 2. What you expected to happen
Update with another suitable package.

### 3. What actually happened
'request' package is still used.

## Environment details
Node.js version
    > 12.6.0

**Comment by mojito317** [comment]
First of all, thanks for your report @anushreemjoshi!

A similar issue was already opened with this request, see https://github.com/cloudant/nodejs-cloudant/issues/415 for more details.

We are currently working on a [new beta sdk](https://github.com/IBM/cloudant-node-sdk) that uses the `axios` package instead. We'll be adding a changes follower to our `axios` based SDK (beta) in due course.

With this in mind, I am closing this issue.
