### ISSUE TITLE
_db_updates timeout doesn't use 'since'

### ISSUE THREAD

**Issue by FelipeTaiarol** [cloudant-labs/cloudant-follow#23]
- cloudant-follow version(s): 0.16.1
- Node version: 6.12

I'm not sure if this is a bug or a missing feature. With PouchDB, if I am listening to the _changes feed and there is a timeout Pouch restart the connection passing the 'since' parameter. cloudant-follow doesn't do it with the _db_updates feed so every time there is a timeout the changes handler receive all databases.

**Comment by smithsz** [comment]
Thanks for raising this issue. You're right. It looks like we don't retry the /_db_updates query using a `since` parameter. Hoping to get a fix out this week.
