### ISSUE TITLE
Support `feed=normal`

### ISSUE THREAD

**Issue by smithsz** [cloudant-labs/cloudant-follow#3]
Allow clients to query a `normal` feed. Ensure the `last_seq` value is emitted to the client. Retry any request failures using a suitable `since` parameter.

Also, ensure `seq_interval` parameter is supported in the implementation (see https://github.com/apache/couchdb-chttpd/blob/master/src/chttpd_db.erl#L1441).

_(Required for https://github.com/cloudant/couchbackup/issues/100)_

**Comment by grapevineai** [comment]
Any news on this?

**Comment by mojito317** [comment]
Hi @grapevineai!

Thank you for your interest, but we have no immediate plans to add this feature.

**Comment by ricellis** [comment]
We won't be adding this.
With the deprecation of [`@cloudant/cloudant`](https://github.com/cloudant/nodejs-cloudant/) in favour of [`@ibm-cloud/cloudant`](https://github.com/IBM/cloudant-node-sdk/) we will no longer be maintaining this fork.
If you are using [Nano](https://github.com/apache/couchdb-nano) you may want to raise an issue there as it has its own internal changes follower now.
