### ISSUE TITLE
Is longpoll currently supported?

### ISSUE THREAD

**Issue by ckoberlein** [cloudant-labs/cloudant-follow#30]
We're currently using the cloudant-follow module via nodejs-cloudant v1.10.0 in our project.

The options being passed in to .follow() are:

```
{
    feed: "longpoll",
    since: "now",
    heartbeat: 60000
}
```

The behavior we're observing is that our change listener is only firing occasionally and is appearing to miss some changes.  We're testing via document modification about 1x per minute at a maximum.

Is the longpoll option fully supported?  Looking at the code, it appears to be (or at least partially), but the documentation says only continuous is allowed.

It's my understanding that longpoll closes the connection, but through this module, it should re-open again?

If longpoll is fully supported, would it be possible to have an example so we can ensure we are using it correctly?

Thanks!

**Comment by smithsz** [comment]
Hi,
We've recently inherited this code and are still in the process of improving it. You're right, the code does indicate this is supported but looking at the commit message in https://github.com/cloudant-labs/cloudant-follow/commit/0343e5af1ea73a004c38415dc750b5ba6a0041f5 I'm dubious as to whether it's really production ready. Our docs currently state that only `continuous` feeds are supported.
I'll raise an issue in our backlog to support this feature (alongside `normal` feeds too).
What are you trying to do? It might be possible to adapt the `continuous` feed to fit your needs.
Regards.

**Comment by ckoberlein** [comment]
Hi Sam,

Thanks for getting back to us quickly!  Continuous mode does seem to work really well in general, but I was looking into `longpoll` because I thought it fit our need better.

Our current use case is monitoring our databases for changes, and then on a change, trigger a Cloudant view call(s) to get the data we're interested in.

My experience was that with `continuous` mode, we'd get a new change notification for each individual change, and if there were several changes arriving in a short period of time, we would end up querying the database via our views repeatedly, which we wanted to avoid also because of Cloudant account throughput limits.

**Comment by ricellis** [comment]
We won't be adding this.
With the deprecation of [`@cloudant/cloudant`](https://github.com/cloudant/nodejs-cloudant/) in favour of [`@ibm-cloud/cloudant`](https://github.com/IBM/cloudant-node-sdk/) we will no longer be maintaining this fork.

It is possible to make [`longpoll` feed requests in `@ibm-cloud/cloudant`](https://cloud.ibm.com/apidocs/cloudant?code=node#postchanges-databases).
