### ISSUE TITLE
Unit tests fail on Node.js v9.8.0

### ISSUE THREAD

**Issue by cluxter** [cloudant-labs/cloudant-follow#47]
* `cloudant-follow` version: `0.17.0-SNAPSHOT`
* Node.js version: `v9.8.0`

Here is what I do to test `cloudant-follow`:

1) `git clone git@github.com:cloudant-labs/cloudant-follow.git`
2) `cd cloudant-follow`
3) `npm install`
4) `cd test`
5) `node couch.js`
This one succeeds.
6) `node follow.js`
This one fails.
7) `node issues.js`
This one fails.
8) `node params.js`
This one fails.
9) `node stream.js`
This one fails.

I suspect the Node.js version to cause this because when I run this in my Node.js program:

```
feed.on("change", function (change) {
    console.log("Change detected:", change)
    this.stop()
})
```

the `this.stop()` line will cause this error and will terminate the program:

```
_http_client.js:354
  if (req.res && req.res.readable) {
          ^

TypeError: Cannot read property 'res' of null
    at Socket.socketCloseListener (_http_client.js:354:11)
    at Socket.emit (events.js:180:13)
    at TCP._handle.close [as _onclose] (net.js:538:12)
```

But maybe the Node.js version is not the source of the problem. I will try to run the tests on another Node.js version tomorrow and I will post the results here.

**Comment by ricellis** [comment]
Thanks for reporting this. FWIW the tests run cleanly for me on Node 8.9.1.

@smithsz is going to update the Jenkins and Travis test versions of Node.js as part of #49 so that might show something up too.

**Comment by cluxter** [comment]
After more extensive testing, here are the results.

* `cloudant-follow` version: `0.17.0-SNAPSHOT`

Unit tests fail both with CouchDB v2.1.1 and Node.js v9.8.0. Only the combination of CouchDB v1.7.1 and Node.js v8.9.1 passes all the tests:

![image](https://user-images.githubusercontent.com/6885295/37437799-692f7690-27ef-11e8-87a1-df90b6f74b79.png)

I opened an issue about the unit tests failing with CouchDB v2.1.1 here: https://github.com/cloudant-labs/cloudant-follow/issues/50
