### ISSUE TITLE
Test failures causing many Greenkeeper issues

### ISSUE THREAD

**Issue by ricellis** [cloudant-labs/cloudant-follow#49]
Please include the following information in your ticket.

- cloudant-follow version(s) that are affected by this issue.
> master
- Node version
> 4,6,8
- A small code sample that demonstrates the issue.
> See Jenkins build history

Something has gone weird with the Jenkins builds and it is causing test failures. When greenkeeper runs builds for newly released in-range versions the tests are failing and this causes
greenkeeper to raise issues.

Also it appears Travis is running different Node.js versions to Jenkins, both should be updated to the 6.x, 8.x, currrent strategy we have been using elsewhere (along with the associated engine 6.x in the package.json).

**Comment by smithsz** [comment]
Fixed in #52.
