### ISSUE TITLE
feed.filter() doesn't get the proper 'req' value

### ISSUE THREAD

**Issue by cluxter** [cloudant-labs/cloudant-follow#54]
* `cloudant-follow` version: `0.17.0-SNAPSHOT`
* Node.js version: `v8.9.1`
* CouchDB version : `1.7.7`

I use this code from the README / Object API section:

```
var follow = require('cloudant-follow');

var opts = {}; // Same options paramters as before
var feed = new follow.Feed(opts);

// You can also set values directly.
feed.db            = "http://example.iriscouch.com/boogie";
feed.since         = 3;
feed.heartbeat     = 30    * 1000
feed.inactivity_ms = 86400 * 1000;

feed.filter = function(doc, req) {
  // req.query is the parameters from the _changes request and also feed.query_params.
  console.log('Filtering for query: ' + JSON.stringify(req.query));

  if(doc.stinky || doc.ugly)
    return false;
  return true;
}

feed.on('change', function(change) {
  console.log('Doc ' + change.id + ' in change ' + change.seq + ' is neither stinky nor ugly.');
})

feed.on('error', function(er) {
  console.error('Since Follow always retries on errors, this must be serious');
  throw er;
})

feed.follow();
```

This part:

```
feed.filter = function(doc, req) {
  // req.query is the parameters from the _changes request and also feed.query_params.
  console.log('Filtering for query: ' + JSON.stringify(req.query));

  if(doc.stinky || doc.ugly)
    return false;
  return true;
}
```
doesn't get the `req` parameter right. It's always set to `{}`.

I tested it with the latest patches from https://github.com/cloudant-labs/cloudant-follow/pull/52 but it didn't change anything.

I identified the code which defines its value: https://github.com/cloudant-labs/cloudant-follow/blob/7805bf0cb70ce30f5fb0bec46edce1cfaf5a126f/lib/feed.js#L670

The `self.pending.request.changes_query` key doesn't exist. However `self` does contain a `query_params` key at its root which contains the expected value. So my guess is we could change this line like this:

```
var req = lib.JDUP({'query': self.query_params});
```

I'm not certain this is the proper way to fix this issue though. Maybe the `self.pending.request.changes_query` key *should* exist.

It looks like we don't have any unit test for this case so writting one would help for the future.

**Comment by smithsz** [comment]
Thanks for raising this @cluxter. I think using `self.query_params` is a suitable fix here. The object gets copied and possibly updated in the `query_feed()` function. I'll add a line to write it back to `self.query_params` at the end of that function. I'll also include a test under test/issues/cloudant-follow.
