### ISSUE TITLE
Unexpected behavior when setting "since" to "now"

### ISSUE THREAD

**Issue by TWry** [cloudant-labs/cloudant-follow#83]
I'm having an issue with the "since" option. If I understand correctly, the docs say that when setting it to "now", the change notifications start at the current revision. Here's my code:

```const follow = require('cloudant-follow')
const opts = {db: "http://admin:secret@localhost:5984/_db_updates", since: "now"}
const feed = new follow.Feed(opts)
feed.filter = (doc, req) => {
	console.log("Filtering for query: " + JSON.stringify(req.query))
	return true
}
feed.on("change", change => console.log(change))
feed.on("error", err => console.error(err))
feed.follow()
```

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue
Run the code above and e.g. create a new database.

### 2. What you expected to happen
change notifications are displayed

### 3. What actually happened
No output whatsoever

Version info:
cloudant-follow 0.17
node 10.11

**Comment by smithsz** [comment]
Thanks, I'll take a look at this one now.
Seems when using a `/_db_updates` feed with `since=now` we end up with an `undefined` since value in the feed URL.

**Comment by TWry** [comment]
Right, this is what I see in the CouchDB logs. It shows a request ending in: `&since=`.
